<?php
define('LANGUAGE', 'fil');
define('SLOGAN', 'Simpleng pag-host ng file');
define('DESCRIPTION', 'Nagawa nang simple ang pag-host ng file. Walang limitasyon. Libreng pagbabahagi ng file sa Starfiles.');
define('SELECTFILE', 'Pumili ng file');
define('UPLOADMULTIPLEFILES', 'I-drop ang mga files o Mag-click Dito');
define('UPLOADSINGLEFILE', 'I-drop ang file o Mag-click Dito');
define('UPLOADFILE', 'Mag-upload ng file');
define('UPLOADFILES', 'Mag-upload ng mga file');
define('JAVASCRIPTWARNING', 'Ang Javascript ay hindi gumagana. Paganahin ito para magamit ang lahat ng features.');
define('VPNWARNING', 'Mukhang ikaw ay gumagamit ng VPN. Maaring hindi gumana ang ilang features habang gumagamit nito.');
define('GOTOUPLOADPAGE', 'Pumunta sa Upload Page');
define('RECENTS', 'Iyong mga Recent Files');
define('ERRORS', 'Errors');
define('NOFILEUPLOADED', 'Walang uploaded file');
define('FILETOOLARGE', 'Malaki ang file');
define('SERVERERROR', 'Error sa Server');
define('PARTIALLYUPLOADED', 'Ang upload ay hindi pa kumpleto');
define('SYNCPROFILES', 'I-sync and mga Profiles');
define('FOOTERDESCRIPTION', 'Ang Startfiles ay libreng file-hosting service para mag-store ng mga files at madaling ibahagi ito.');
define('HELPTEXT', 'I-report ang mga issue at mag-request ng mga features sa pamamagitan ng ');
define('TOS', 'Terms of Service');
define('PRIVACY', 'Privacy Policy');
define('API', 'API (Developer Tools)');
define('MADEBY', 'Ginawa ng');
define('JSHELPANDQUEUE', 'Javascript Improvement & Queueing System');
define('DESIGNERS', 'Mga nagdisenyo');
define('HOME', 'Home');
define('BASICFILEUPLOAD', 'Basic File Upload');
define('NAME', 'Pangalan');
define('CONTENTS', 'Nilalaman');
define('EXAMPLE', 'Halimbawa');
define('CHUNKEDFILEUPLOAD', 'Chunked File Upload');
define('CHUNKEXPLANATION', 'Ang mga Chunks ay paghahati ng file hanggang 2MB (<span class="code">2097152</span> bytes). Ulitin ang mga sumusunod para bawat chunk');
define('FILE', 'file');
define('CHUNKCOUNT', 'bilang ng chunk');
define('CHUNKNUMBER', 'numero ng chunk');
define('CHUNKUSAGE', 'Ang huling na-upload na chunk ay ibabalik ang file ID. Gamitin ito tulad nito');
define('FILENOTFOUND', 'Hindi natagpuan ang file');
define('FILEDELETED', 'Burado na ang file');
define('PASSWORD', 'Password');
define('PASSWORDPROTECTED', 'Protektado ang Password');
define('PASSWORDINCORRECT', 'Mali ang Password');
define('ENTERPASSWORD', 'Maglagay ng Password');
define('LOGIN', 'Login');
define('DIRECTURL', 'Direct URL');
define('DOWNLOAD', 'Download');
define('DOWNLOADS', 'Downloads');
define('DELETE', 'Burahin');
define('REMOVEFROMPROFILE', 'Alisin sa Profile');
define('REPORT', 'I-report ang File');
define('SAVE', 'I-save');