<?php
define('LANGUAGE', 'tr');
define('SLOGAN', 'Temel Dosya Hizmeti Gerçekleşti');
define('DESCRIPTION', 'Temel Dosya Hizmeti Gerçekleşti. Limitsiz hesapsız dosya barındırma. Dosyaları Starfiles ile ücretsiz olarak kolayca paylaşın.');
define('SELECTFILE', 'Dosya Seç');
define('UPLOADMULTIPLEFILES', 'Dosyaları Sürükle veya Buraya Tıkla');
define('UPLOADSINGLEFILE', 'Dosyayı Sürükle veya Buraya Tıkla');
define('UPLOADFILE', 'Dosya Yükle');
define('UPLOADFILES', 'Dosyaları Yükle');
define('JAVASCRIPTWARNING', 'Javascript etkin değil. Lütfen tüm özellikleri etkinleştirmek için etkinleştirin.');
define('VPNWARNING', 'Bir VPN tespit ettik. VPN kullanmak bazı özellikleri bozabilir.');
define('GOTOUPLOADPAGE', 'Yükleme Sayfasına Git');
define('RECENTS', 'Son Veriler');
define('ERRORS', 'Hatalar');
define('NOFILEUPLOADED', 'Yüklenen Dosya Yok');
define('FILETOOLARGE', 'Dosya Boyutu Çok Büyük');
define('SERVERERROR', 'Sunucu Hatası');
define('PARTIALLYUPLOADED', 'Kısmen Yüklendi');
define('SYNCPROFILES', 'Profilleri Senkronize Et');
define('FOOTERDESCRIPTION', 'Starfiles, kullanıcıların dosyaları depolamasına ve kolayca paylaşmasına olanak tanıyan ücretsiz bir dosya barındırma hizmetidir..');
define('HELPTEXT', 'Lütfen karşılaştığınız sorunları bildirin ve özellik isteklerin'de bulunun ');
define('TOS', 'Kullanım Şartları');
define('PRIVACY', 'Gizlilik Politikası');
define('API', 'API (Geliştirici Araçları)');
define('MADEBY', 'Tarafından yapıldı');
define('JSHELPANDQUEUE', 'Javascript Geliştirme ve Kuyruk Sistemi');
define('DESIGNERS', 'Tasarımcılar');
define('HOME', 'Ana Sayfa');
define('BASICFILEUPLOAD', 'Temel Dosya Yükle');
define('NAME', 'İsim');
define('CONTENTS', 'İçerikler');
define('EXAMPLE', 'Örnek');
define('CHUNKEDFILEUPLOAD', 'Dosya Yığını Yükle');
define('CHUNKEXPLANATION', 'Dosya yığınını 2MB'a kadar olan parçalara ayrılır. (<span class="code">2097152</span> bytes). Her yığın için aşağıdakileri tekrarlayın');
define('FILE', 'Dosya');
define('CHUNKCOUNT', 'Yığın Sayısı');
define('CHUNKNUMBER', 'Yığın Numarası');
define('CHUNKUSAGE', 'Yüklenen son yığın dosya kimliğini döndürür. Bu şekilde kullanın');
define('FILENOTFOUND', 'Dosya Bulunamadı');
define('FILEDELETED', 'Dosya Silindi');
define('PASSWORD', 'Şifre');
define('PASSWORDPROTECTED', 'Şifre Korumalı');
define('PASSWORDINCORRECT', 'Şifre Geçersiz');
define('ENTERPASSWORD', 'Bir Şifre Girin');
define('LOGIN', 'Giriş');
define('DIRECTURL', 'Doğrudan URL');
define('DOWNLOAD', 'İndir');
define('DOWNLOADS', 'İndirmeler');
define('DELETE', 'Sil');
define('REMOVEFROMPROFILE', 'Profilden Kaldır');
define('REPORT', 'Dosya Bildir');
define('SAVE', 'Kaydet');
